### ISSUE TITLE
Need for new work order status system

### ISSUE THREAD

**Issue by scaspers** [scaspers/D3-API#5]
enumerated status' that can used in API and in PICK.  PICK will own this.
[Proposed definitions](https://docs.google.com/spreadsheets/d/1GhVTRwj8GXdf7GOHxaAH8Ts4M_T_0eLdc8rXRYdik3E/edit#gid=0)

**Comment by DanielCaspers** [comment]
Should we also be attaching the user or employee ID responsible for moving it from one stage to the next?

I am wondering because I noticed I don't have an employee# returned on the list of work orders, but perhaps we have a more general problem here that should be addressed. 

If you don't think so, LMK if you want me to open a separate ticket for that field on the work order

**Comment by scaspers** [comment]
Soon to come will be a field with the assigned tech and assigned service writer.

**Comment by scaspers** [comment]
there is now a field "techNum" that has the employee number of the technician assigned to the order.  If there is none assigned yet then it will return 0 (zero).
The data is returned as an integer.

**Comment by DanielCaspers** [comment]
Adapted to grab property and map it into the client.

We can define if you want different display of empty tech number, but here is it right now.

![image](https://user-images.githubusercontent.com/6056563/27615597-00291234-5b6f-11e7-962c-bb5887c1d054.png)

**Comment by scaspers** [comment]
Would it be better to return null?

**Comment by DanielCaspers** [comment]
I think you've completed this? And I've integrated? Time to close?
